services:
  deferdataloading:
    container_name: container-name
    image: vladteresch/deferdataloading:latest
    networks:
      - app-net
    environment:
      - Connections__DbName=PostgreSql
      - "Connections__DbConnection=Host=postgres;Database=mydatabase;Username=test_user;Password=test_password"
      - "Connections__MongoDbConnection=mongodb://test:test@mongodb:27017"
      - Connections__MongoDbName=MongoDbName
      - Connections__RabbitMqHostName=rabbitmq
      - Connections__RabbitMqPort=5672
      - Connections__RabbitMqUser=test
      - Connections__RabbitMqPassword=test
      - Connections__QueueName=example_rabbitmq_queue
      - Connections__SeqKey=example_seqkey
      - "Connections__SeqHost=http://seq:5341"
      - Connections__WorkerDelayed=180

networks:
  test-network:
    external: true
    name: app-net   